--- # simple script for ignoring the errors
- hosts: all
  become: yes
  tasks:
    - name: getting the url
      get_url:
        url: "http://{{ item }}/index.html"
        dest: "/tmp/{{ item }}"
      ignore_errors: yes
      with_items:
       - node1
       - node2
       - node3
