--- # installing http servers with node names
- hosts: centos
  become: yes
  handlers:
    - name: restarting the httpd service
      service:
        name: httpd
        state: restarted
      tags:
        - restarting
      listen:
        - "restart"
  tasks:
    - name: installing the httpd package
      yum:
        name: httpd
        state: latest
      tags:
        - software
    - name: starting the httpd service
      service:
        name: httpd
        state: started
        enabled: yes
      tags:
        - service
    - name: creating the configuration file
      file:
        path: /var/www/html/index.html
        state: touch
        mode: 0644
        owner: ansible
        group: ansible
      tags:
        - file
    - name: changing the line date into the file
      lineinfile:
        path: /var/www/html/index.html
        line: "This website is working fine"
      tags:
        - config
      notify:
        - "restart"
