#sample script for installing and configuring the web application
---
- hosts: webservers
  become: yes
  vars_files:
    - /home/ansible/confidential
  tasks:
    - name: installing httpd
      yum:
        name: httpd
        state: latest
      notify: restart
      tags:
        - base-install
    - name: configure vhost
      template:
        src: /home/ansible/vhost.conf.j2
        dest: /etc/httpd/conf.d/vhost.conf
      notify: restart
      tags:
        - vhost
    - name: configure site auth
      template:
        src: /home/ansible/htpasswd.j2
        dest: /etc/httpd/conf/htpasswd
      notify: restart
      tags:
        - vhost
    - name: command mode to run the datajob
      command: /opt/data-job.sh
      async: 600
      poll: 0
      tags:
        - data-job
  handlers:
    - name: restarting the service
      service:
        name: httpd
        state: restarted
        enabled: yes
      listen: restart
